# Generated by Django 3.2.9 on 2021-11-26 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kullanci',
            old_name='K_Turu',
            new_name='k_Turu',
        ),
    ]
