# Generated by Django 3.2.9 on 2021-11-26 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20211126_2249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kullanci',
            name='k_Turu',
        ),
    ]
