# Generated by Django 3.2.9 on 2021-11-26 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_alter_kullanci_kayittarihi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kullanci',
            name='kayitTarihi',
        ),
    ]
