# Generated by Django 3.2.9 on 2021-11-28 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_remove_kullanci_kayittarihi'),
    ]

    operations = [
        migrations.AddField(
            model_name='kullanci',
            name='k_Turu',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='KullaniciTurleri', to='todo.k_turu'),
        ),
    ]
