# Generated by Django 3.2.9 on 2021-12-01 00:55

from django.db import migrations, models
import todo.models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_kullanci_k_turu'),
    ]

    operations = [
        migrations.AddField(
            model_name='kullanci',
            name='k_avatar',
            field=models.ImageField(null=True, upload_to=todo.models.generate_filename),
        ),
        migrations.AlterField(
            model_name='ogretmen',
            name='ogr_tanitim',
            field=models.FileField(upload_to=todo.models.generate_filename),
        ),
    ]
