# Generated by Django 3.2.9 on 2021-12-01 00:59

from django.db import migrations, models
import todo.models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_auto_20211201_0355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ogretmen',
            name='ogr_tanitim',
            field=models.FileField(upload_to=todo.models.generate_for_filname_teacher),
        ),
    ]
