# Generated by Django 3.2.9 on 2021-12-01 01:16

from django.db import migrations, models
import todo.models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_alter_ogretmen_ogr_tanitim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kullanci',
            name='k_avatar',
            field=models.ImageField(default=None, null=True, upload_to=todo.models.generate_filename),
        ),
    ]
