# Generated by Django 3.2.9 on 2021-12-01 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0010_alter_kullanci_k_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kullanci',
            name='k_avatar',
            field=models.ImageField(default=None, null=True, upload_to=''),
        ),
    ]
