# Generated by Django 3.2.9 on 2021-12-01 01:18

from django.db import migrations, models
import todo.models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0011_alter_kullanci_k_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kullanci',
            name='k_avatar',
            field=models.ImageField(blank=True, default=None, upload_to=todo.models.generate_filename),
        ),
    ]
