# Generated by Django 3.2.9 on 2021-12-06 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0012_alter_kullanci_k_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ogretmen',
            name='k_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.kullanci', unique=True),
        ),
    ]
