# Generated by Django 3.2.9 on 2021-12-06 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0013_alter_ogretmen_k_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ogretmen',
            name='k_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='todo.kullanci'),
        ),
    ]
