# Generated by Django 3.2.9 on 2021-12-06 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0015_auto_20211207_0155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kullanci',
            name='k_ilgi',
        ),
        migrations.AddField(
            model_name='kullanci',
            name='k_ilgi',
            field=models.ManyToManyField(to='todo.Ilgi_Alanlari'),
        ),
    ]
