# Generated by Django 3.2.9 on 2021-12-06 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0016_auto_20211207_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kullanci',
            name='k_ilgi',
            field=models.ManyToManyField(related_name='ilgi', to='todo.Ilgi_Alanlari'),
        ),
    ]
