# Generated by Django 3.2.9 on 2021-12-07 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0017_alter_kullanci_k_ilgi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kullanci',
            name='k_ilgi',
            field=models.ManyToManyField(related_name='Ilgi_Alanlari', to='todo.Ilgi_Alanlari'),
        ),
    ]
