# Generated by Django 3.2.9 on 2022-01-15 02:11

from django.db import migrations, models
import django.db.models.deletion
import todo.models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0018_alter_kullanci_k_ilgi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(default='Please enter course name', max_length=50, verbose_name='CourseName')),
                ('coursePhoto', models.ImageField(blank=True, default=None, upload_to=todo.models.generate_filename_coursePhoto)),
                ('coursePrice', models.IntegerField()),
                ('courseAuthor', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='Teacher', to='todo.ogretmen')),
            ],
        ),
    ]
