# Generated by Django 3.2.9 on 2022-01-17 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0019_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kullanci',
            name='k_ilgi',
            field=models.ManyToManyField(null=True, related_name='Ilgi_Alanlari', to='todo.Ilgi_Alanlari'),
        ),
    ]
