# Generated by Django 3.2.9 on 2022-01-20 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0020_alter_kullanci_k_ilgi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='k_turu',
            name='Aciklama',
        ),
        migrations.AlterField(
            model_name='kullanci',
            name='k_ilgi',
            field=models.ManyToManyField(related_name='Ilgi_Alanlari', to='todo.Ilgi_Alanlari'),
        ),
    ]
