# Generated by Django 3.2.9 on 2022-01-28 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0022_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kullanci',
            name='k_ilgi',
            field=models.ManyToManyField(default=None, related_name='Ilgi_Alanlari', to='todo.Ilgi_Alanlari'),
        ),
    ]
