# Generated by Django 3.2.9 on 2022-01-28 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0023_alter_kullanci_k_ilgi'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
